# Generated by Django 3.2.8 on 2021-12-27 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='question',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='query.question'),
            preserve_default=False,
        ),
    ]
