# Generated by Django 3.2.8 on 2021-12-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_survey_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='query.answer'),
            preserve_default=False,
        ),
    ]
