# Generated by Django 3.2.8 on 2021-12-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_auto_20211227_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(blank=True, default='No answer', null=True, on_delete=django.db.models.deletion.CASCADE, to='query.answer'),
        ),
    ]
