# Generated by Django 3.2.8 on 2021-12-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='query.answer'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='date_ended',
            field=models.DateField(),
        ),
    ]
